# Generated by Django 3.1.3 on 2020-11-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Starting_Balence', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Of_Transaction', models.DateField()),
                ('Type_Of_Transaction', models.CharField(choices=[('1', 'Deposit'), ('2', 'Withdraw')], max_length=1)),
            ],
        ),
    ]
