# Generated by Django 3.1.3 on 2020-11-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Account_It_Applies_To',
            field=models.CharField(default='Me', max_length=60),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Description',
            field=models.CharField(default='Hello', max_length=300),
        ),
    ]
