# Generated by Django 3.1.3 on 2020-11-13 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0002_auto_20201111_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date_Of_Transaction',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='type_Of_Transaction',
            new_name='type',
        ),
    ]
