# Generated by Django 3.1.3 on 2020-11-08 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0002_auto_20201104_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Starting_Balence',
            new_name='Starting_Balance',
        ),
    ]
